version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    command: "postgres"
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 127.0.0.1:5432:5432